// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace TasKing.Migrations
{
    [DbContext(typeof(TasKingContext))]
    [Migration("20220503121929_V2")]
    partial class V2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.ClanOrganizacije", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("administrator")
                        .HasColumnType("bit");

                    b.Property<bool>("izbacen")
                        .HasColumnType("bit");

                    b.Property<int?>("korisnikID")
                        .HasColumnType("int");

                    b.Property<int?>("organizacijaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("vremePosecivanja")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("korisnikID");

                    b.HasIndex("organizacijaID");

                    b.ToTable("Clan organizacije");
                });

            modelBuilder.Entity("Models.ClanTima", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("clanOgranizacijeID")
                        .HasColumnType("int");

                    b.Property<bool>("izbacen")
                        .HasColumnType("bit");

                    b.Property<int?>("timID")
                        .HasColumnType("int");

                    b.Property<bool>("vodjaTima")
                        .HasColumnType("bit");

                    b.Property<DateTime>("vremePosecivanja")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("clanOgranizacijeID");

                    b.HasIndex("timID");

                    b.ToTable("Clan tima");
                });

            modelBuilder.Entity("Models.Korisnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("brTelefona")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("korisnickoIme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("lozinka")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("prezime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("profilnaSlika")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Korisnik");
                });

            modelBuilder.Entity("Models.Organizacija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("aktivna")
                        .HasColumnType("bit");

                    b.Property<DateTime>("datumOsnivanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("kod")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("slika")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Organizacija");
                });

            modelBuilder.Entity("Models.PozivUOrganizaciju", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("organizacijaID")
                        .HasColumnType("int");

                    b.Property<int>("pozvaniKorisnikID")
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("vremePoziva")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("organizacijaID");

                    b.HasIndex("pozvaniKorisnikID");

                    b.ToTable("Poziv u organizaciju");
                });

            modelBuilder.Entity("Models.PozivUTim", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("pozvaniKorisnikID")
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<int>("timID")
                        .HasColumnType("int");

                    b.Property<DateTime>("vremePoziva")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("pozvaniKorisnikID");

                    b.HasIndex("timID");

                    b.ToTable("Poziv u tim");
                });

            modelBuilder.Entity("Models.Projekat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("opis")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<int>("timID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("timID");

                    b.ToTable("Projekat");
                });

            modelBuilder.Entity("Models.Task", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("clanTimaID")
                        .HasColumnType("int");

                    b.Property<string>("naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("opis")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("projekatID")
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<string>("tip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vrednost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("clanTimaID");

                    b.HasIndex("projekatID");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("Models.Tim", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("aktivan")
                        .HasColumnType("bit");

                    b.Property<DateTime>("datumOsnivanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("kod")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("slika")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Tim");
                });

            modelBuilder.Entity("Models.ClanOrganizacije", b =>
                {
                    b.HasOne("Models.Korisnik", "korisnik")
                        .WithMany("clanoviOrganizacije")
                        .HasForeignKey("korisnikID");

                    b.HasOne("Models.Organizacija", "organizacija")
                        .WithMany("clanoviOrganizacije")
                        .HasForeignKey("organizacijaID");

                    b.Navigation("korisnik");

                    b.Navigation("organizacija");
                });

            modelBuilder.Entity("Models.ClanTima", b =>
                {
                    b.HasOne("Models.ClanOrganizacije", "clanOgranizacije")
                        .WithMany("clanoviTima")
                        .HasForeignKey("clanOgranizacijeID");

                    b.HasOne("Models.Tim", "tim")
                        .WithMany("clanoviTima")
                        .HasForeignKey("timID");

                    b.Navigation("clanOgranizacije");

                    b.Navigation("tim");
                });

            modelBuilder.Entity("Models.PozivUOrganizaciju", b =>
                {
                    b.HasOne("Models.Organizacija", "organizacija")
                        .WithMany("poziviUOrganizaciju")
                        .HasForeignKey("organizacijaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Korisnik", "pozvaniKorisnik")
                        .WithMany("primljeniPoziviIzOrganizacije")
                        .HasForeignKey("pozvaniKorisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("organizacija");

                    b.Navigation("pozvaniKorisnik");
                });

            modelBuilder.Entity("Models.PozivUTim", b =>
                {
                    b.HasOne("Models.Korisnik", "pozvaniKorisnik")
                        .WithMany("primljeniPoziviIzTima")
                        .HasForeignKey("pozvaniKorisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Tim", "tim")
                        .WithMany("poziviUTim")
                        .HasForeignKey("timID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pozvaniKorisnik");

                    b.Navigation("tim");
                });

            modelBuilder.Entity("Models.Projekat", b =>
                {
                    b.HasOne("Models.Tim", "tim")
                        .WithMany("projekti")
                        .HasForeignKey("timID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tim");
                });

            modelBuilder.Entity("Models.Task", b =>
                {
                    b.HasOne("Models.ClanTima", "clanTima")
                        .WithMany("taskovi")
                        .HasForeignKey("clanTimaID");

                    b.HasOne("Models.Projekat", "projekat")
                        .WithMany("taskovi")
                        .HasForeignKey("projekatID");

                    b.Navigation("clanTima");

                    b.Navigation("projekat");
                });

            modelBuilder.Entity("Models.ClanOrganizacije", b =>
                {
                    b.Navigation("clanoviTima");
                });

            modelBuilder.Entity("Models.ClanTima", b =>
                {
                    b.Navigation("taskovi");
                });

            modelBuilder.Entity("Models.Korisnik", b =>
                {
                    b.Navigation("clanoviOrganizacije");

                    b.Navigation("primljeniPoziviIzOrganizacije");

                    b.Navigation("primljeniPoziviIzTima");
                });

            modelBuilder.Entity("Models.Organizacija", b =>
                {
                    b.Navigation("clanoviOrganizacije");

                    b.Navigation("poziviUOrganizaciju");
                });

            modelBuilder.Entity("Models.Projekat", b =>
                {
                    b.Navigation("taskovi");
                });

            modelBuilder.Entity("Models.Tim", b =>
                {
                    b.Navigation("clanoviTima");

                    b.Navigation("poziviUTim");

                    b.Navigation("projekti");
                });
#pragma warning restore 612, 618
        }
    }
}
