// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace TasKing.Migrations
{
    [DbContext(typeof(TasKingContext))]
    partial class TasKingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.ClanOrganizacije", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("administrator")
                        .HasColumnType("bit");

                    b.Property<bool>("izbacen")
                        .HasColumnType("bit");

                    b.Property<int?>("korisnikIDID")
                        .HasColumnType("int");

                    b.Property<int?>("organizacijaIDID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("korisnikIDID");

                    b.HasIndex("organizacijaIDID");

                    b.ToTable("Clan organizacije");
                });

            modelBuilder.Entity("Models.ClanTima", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("clanOgranizacijeIDID")
                        .HasColumnType("int");

                    b.Property<bool>("izbacen")
                        .HasColumnType("bit");

                    b.Property<int?>("timIDID")
                        .HasColumnType("int");

                    b.Property<bool>("vodjaTima")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("clanOgranizacijeIDID");

                    b.HasIndex("timIDID");

                    b.ToTable("Clan tima");
                });

            modelBuilder.Entity("Models.Korisnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("korisnickoIme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("lozinka")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("prezime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("profilnaSlika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Korisnik");
                });

            modelBuilder.Entity("Models.Organizacija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("aktivna")
                        .HasColumnType("bit");

                    b.Property<DateTime>("datumOsnivanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("slika")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("vremePosecivanja")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Organizacija");
                });

            modelBuilder.Entity("Models.Projekat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("opis")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<int>("timIDID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("timIDID");

                    b.ToTable("Projekat");
                });

            modelBuilder.Entity("Models.Task", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("clanTimaID")
                        .HasColumnType("int");

                    b.Property<string>("naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("opis")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("projekatID")
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<string>("tip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vrednost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("clanTimaID");

                    b.HasIndex("projekatID");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("Models.Tim", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("aktivan")
                        .HasColumnType("bit");

                    b.Property<DateTime>("datumOsnivanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("slika")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("vremePosecivanja")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Tim");
                });

            modelBuilder.Entity("Models.ClanOrganizacije", b =>
                {
                    b.HasOne("Models.Korisnik", "korisnikID")
                        .WithMany("clanoviOrganizacije")
                        .HasForeignKey("korisnikIDID");

                    b.HasOne("Models.Organizacija", "organizacijaID")
                        .WithMany("clanoviOrganizacije")
                        .HasForeignKey("organizacijaIDID");

                    b.Navigation("korisnikID");

                    b.Navigation("organizacijaID");
                });

            modelBuilder.Entity("Models.ClanTima", b =>
                {
                    b.HasOne("Models.ClanOrganizacije", "clanOgranizacijeID")
                        .WithMany("clanoviTima")
                        .HasForeignKey("clanOgranizacijeIDID");

                    b.HasOne("Models.Tim", "timID")
                        .WithMany("clanoviTima")
                        .HasForeignKey("timIDID");

                    b.Navigation("clanOgranizacijeID");

                    b.Navigation("timID");
                });

            modelBuilder.Entity("Models.Projekat", b =>
                {
                    b.HasOne("Models.Tim", "timID")
                        .WithMany("projekti")
                        .HasForeignKey("timIDID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("timID");
                });

            modelBuilder.Entity("Models.Task", b =>
                {
                    b.HasOne("Models.ClanTima", "clanTima")
                        .WithMany("taskovi")
                        .HasForeignKey("clanTimaID");

                    b.HasOne("Models.Projekat", "projekat")
                        .WithMany("taskovi")
                        .HasForeignKey("projekatID");

                    b.Navigation("clanTima");

                    b.Navigation("projekat");
                });

            modelBuilder.Entity("Models.ClanOrganizacije", b =>
                {
                    b.Navigation("clanoviTima");
                });

            modelBuilder.Entity("Models.ClanTima", b =>
                {
                    b.Navigation("taskovi");
                });

            modelBuilder.Entity("Models.Korisnik", b =>
                {
                    b.Navigation("clanoviOrganizacije");
                });

            modelBuilder.Entity("Models.Organizacija", b =>
                {
                    b.Navigation("clanoviOrganizacije");
                });

            modelBuilder.Entity("Models.Projekat", b =>
                {
                    b.Navigation("taskovi");
                });

            modelBuilder.Entity("Models.Tim", b =>
                {
                    b.Navigation("clanoviTima");

                    b.Navigation("projekti");
                });
#pragma warning restore 612, 618
        }
    }
}
